<%@ Page Title="" Language="C#" MasterPageFile="~/Em.master" AutoEventWireup="true" CodeFile="Contactus.aspx.cs" Inherits="Contactus" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">


<div style="height:auto; width:auto">

  <div style="height:500px; width:1000px;  margin-left:150px; background-color:White">

      <h1 id="page-title" 
          style="margin: 0px; padding: 0px 10px 17px; font-size: 42px; font-weight: bold; font-family: caecilia-b7, caecilia, Georgia, Palatino, 'Palatino Linotype', Times, 'Times New Roman', serif; color: rgb(55, 133, 163); line-height: 48px; width: auto; font-style: normal; font-variant: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
          Contact us</h1>
      <p style="margin: 0px; padding: 0px 10px 17px; font-size: 42px; font-weight: bold; font-family: caecilia-b7, caecilia, Georgia, Palatino, 'Palatino Linotype', Times, 'Times New Roman', serif; color: rgb(55, 133, 163); line-height: 48px; width: auto; font-style: normal; font-variant: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
          <span style="color: rgb(68, 68, 68); font-family: helvetica-web-n4, helvetica-web, Helvetica, 'Helvetica Neue', Arial, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18.9799995422363px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 255, 255);">
          If you wish to write to DigiPost.com the address is: Customer Service, R 
          Vadodara, 2 Sugar Court, Prabhat, Harni, 390056.&nbsp; Vadodara&nbsp;&nbsp; 
          Gujarat Please note we are unable to offer help over the phone or email about 
          your Problem and &nbsp;If you have a question about a Transaction, please 
          submit it through the&nbsp;</span><a href="Home.aspx" 
              style="margin: 0px; padding: 0px; color: rgb(0, 116, 189); text-decoration: none; font-family: helvetica-web-n4, helvetica-web, Helvetica, 'Helvetica Neue', Arial, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18.9799995422363px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; border: 0px; vertical-align: baseline; background-color: rgb(255, 255, 255);" 
              title="Q&amp;As">separate Q&amp;A form</a><span 
              style="color: rgb(68, 68, 68); font-family: helvetica-web-n4, helvetica-web, Helvetica, 'Helvetica Neue', Arial, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18.9799995422363px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 255, 255);">.</span></p>
      <p style="margin: 0px; padding: 0px 10px 17px; font-size: 22px; font-weight: bold; font-family: caecilia-b7, caecilia, Georgia, Palatino, 'Palatino Linotype', Times, 'Times New Roman', serif; color: rgb(55, 133, 163); line-height: 48px; width: auto; font-style: normal; font-variant: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
         Email:support@DigiPost.com</p>
       <p style="margin: 0px; padding: 0px 10px 17px; font-size: 22px; font-weight: bold; font-family: caecilia-b7, caecilia, Georgia, Palatino, 'Palatino Linotype', Times, 'Times New Roman', serif; color: rgb(55, 133, 163); line-height: 48px; width: auto; font-style: normal; font-variant: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
         24/7 HelpLine:8000-1000-200</p>
      <p style="margin: 0px; padding: 0px 10px 17px; font-size: 22px; font-weight: bold; font-family: caecilia-b7, caecilia, Georgia, Palatino, 'Palatino Linotype', Times, 'Times New Roman', serif; color: rgb(55, 133, 163); line-height: 48px; width: auto; font-style: normal; font-variant: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
        Address:</p>
      <p style="margin: 0px; padding: 0px 10px 17px; font-size: 42px; font-weight: bold; font-family: caecilia-b7, caecilia, Georgia, Palatino, 'Palatino Linotype', Times, 'Times New Roman', serif; color: rgb(55, 133, 163); line-height: 48px; width: auto; font-style: normal; font-variant: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); height: 27px;">
          <span style="color: rgb(68, 68, 68); font-family: helvetica-web-n4, helvetica-web, Helvetica, 'Helvetica Neue', Arial, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18.9799995422363px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 255, 255);">
          &nbsp;R Squred Ltd, 2 Sugar Brook Court</span></p>
      <p style="margin: 0px; padding: 0px 10px 17px; font-size: 42px; font-weight: bold; font-family: caecilia-b7, caecilia, Georgia, Palatino, 'Palatino Linotype', Times, 'Times New Roman', serif; color: rgb(55, 133, 163); line-height: 48px; width: auto; font-style: normal; font-variant: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); height: 21px;">
          <span style="color: rgb(68, 68, 68); font-family: helvetica-web-n4, helvetica-web, Helvetica, 'Helvetica Neue', Arial, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18.9799995422363px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 255, 255);">
          &nbsp;Prabhat,Harni, 390056</span></p>
      <p style="margin: 0px; padding: 0px 10px 17px; font-size: 42px; font-weight: bold; font-family: caecilia-b7, caecilia, Georgia, Palatino, 'Palatino Linotype', Times, 'Times New Roman', serif; color: rgb(55, 133, 163); line-height: 48px; width: auto; font-style: normal; font-variant: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); height: 30px;">
          <span style="color: rgb(68, 68, 68); font-family: helvetica-web-n4, helvetica-web, Helvetica, 'Helvetica Neue', Arial, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18.9799995422363px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 255, 255);">
          &nbsp;Gujrat India Vadodara, </span></p>
      <p style="margin: 0px; padding: 0px 10px 17px; font-size: 42px; font-weight: bold; font-family: caecilia-b7, caecilia, Georgia, Palatino, 'Palatino Linotype', Times, 'Times New Roman', serif; color: rgb(55, 133, 163); line-height: 48px; width: auto; font-style: normal; font-variant: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); height: 31px;">
          <span style="color: rgb(68, 68, 68); font-family: helvetica-web-n4, helvetica-web, Helvetica, 'Helvetica Neue', Arial, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 18.9799995422363px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(255, 255, 255);">
          &nbsp;Office No : 0265-6696669 </span></p>

  </div>

  </div>
</asp:Content>

